export type PecaLoja = {
  slug: string;
  nome: string;
  categoria: string;
  precoMinimo: number;
  precoTexto: string;
  tipoPreco: 'fixo';
  descricao: string;
  garantiaDias: number;
  imagemUrl: string;
  tipo: 'peca';
  servicoRelacionado: string;
  keywords: string[];
};

export const PECAS_CATALOGO: PecaLoja[] = [
  {
    slug: 'peca-tomada-simples',
    nome: 'Tomada 10A simples',
    categoria: 'eletricista',
    precoMinimo: 24.9,
    precoTexto: 'R$ 24,90',
    tipoPreco: 'fixo',
    descricao: 'Tomada 2P+T 10A, padrão brasileiro. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-tomada/tipoTomada/simples.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-tomada',
    keywords: ['tomada', 'tom', '10a', 'simples', 'peca', 'pecas', 'plugue'],
  },
  {
    slug: 'peca-tomada-dupla',
    nome: 'Tomada 10A dupla',
    categoria: 'eletricista',
    precoMinimo: 34.9,
    precoTexto: 'R$ 34,90',
    tipoPreco: 'fixo',
    descricao: 'Tomada dupla 10A. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-tomada/tipoTomada/dupla.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-tomada',
    keywords: ['tomada', 'tom', 'dupla', '10a', 'peca'],
  },
  {
    slug: 'peca-tomada-20a',
    nome: 'Tomada 20A',
    categoria: 'eletricista',
    precoMinimo: 39.9,
    precoTexto: 'R$ 39,90',
    tipoPreco: 'fixo',
    descricao: 'Tomada 20A para ar-condicionado, chuveiro ou forno. Peça avulsa.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-tomada/tipoTomada/tomada-20a.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-tomada',
    keywords: ['tomada', 'tom', '20a', 'ar-condicionado', 'peca'],
  },
  {
    slug: 'peca-interruptor-simples',
    nome: 'Interruptor simples',
    categoria: 'eletricista',
    precoMinimo: 22.9,
    precoTexto: 'R$ 22,90',
    tipoPreco: 'fixo',
    descricao: 'Interruptor simples para iluminação. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-interruptor/tipoInterruptor/simples.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-interruptor',
    keywords: ['interruptor', 'interrup', 'luz', 'botao', 'peca'],
  },
  {
    slug: 'peca-interruptor-duplo',
    nome: 'Interruptor duplo',
    categoria: 'eletricista',
    precoMinimo: 29.9,
    precoTexto: 'R$ 29,90',
    tipoPreco: 'fixo',
    descricao: 'Interruptor duplo. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-interruptor/tipoInterruptor/duplo.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-interruptor',
    keywords: ['interruptor', 'duplo', 'luz', 'peca'],
  },
  {
    slug: 'peca-interruptor-paralelo',
    nome: 'Interruptor paralelo',
    categoria: 'eletricista',
    precoMinimo: 29.9,
    precoTexto: 'R$ 29,90',
    tipoPreco: 'fixo',
    descricao: 'Interruptor paralelo (three-way). Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-interruptor/tipoInterruptor/paralelo.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-interruptor',
    keywords: ['interruptor', 'paralelo', 'three way', 'peca'],
  },
  {
    slug: 'peca-disjuntor-monopolar',
    nome: 'Disjuntor monopolar',
    categoria: 'eletricista',
    precoMinimo: 49.9,
    precoTexto: 'R$ 49,90',
    tipoPreco: 'fixo',
    descricao: 'Disjuntor monopolar para quadro de energia. Peça avulsa.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-disjuntor/tipoDisjuntor/monopolar.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-disjuntor',
    keywords: ['disjuntor', 'monopolar', 'quadro', 'peca'],
  },
  {
    slug: 'peca-disjuntor-bipolar',
    nome: 'Disjuntor bipolar',
    categoria: 'eletricista',
    precoMinimo: 69.9,
    precoTexto: 'R$ 69,90',
    tipoPreco: 'fixo',
    descricao: 'Disjuntor bipolar. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-disjuntor/tipoDisjuntor/bipolar.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-disjuntor',
    keywords: ['disjuntor', 'bipolar', 'quadro', 'peca'],
  },
  {
    slug: 'peca-disjuntor-tripolar',
    nome: 'Disjuntor tripolar',
    categoria: 'eletricista',
    precoMinimo: 89.9,
    precoTexto: 'R$ 89,90',
    tipoPreco: 'fixo',
    descricao: 'Disjuntor tripolar. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-disjuntor/tipoDisjuntor/tripolar.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-disjuntor',
    keywords: ['disjuntor', 'tripolar', 'quadro', 'peca'],
  },
  {
    slug: 'peca-torneira-convencional',
    nome: 'Torneira convencional',
    categoria: 'hidraulica',
    precoMinimo: 79.9,
    precoTexto: 'R$ 79,90',
    tipoPreco: 'fixo',
    descricao: 'Torneira de mesa convencional. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-torneira/tipoTorneira/convencional.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-torneira',
    keywords: ['torneira', 'pia', 'peca', 'hidraulica'],
  },
  {
    slug: 'peca-torneira-gourmet',
    nome: 'Torneira gourmet',
    categoria: 'hidraulica',
    precoMinimo: 189.9,
    precoTexto: 'R$ 189,90',
    tipoPreco: 'fixo',
    descricao: 'Torneira gourmet com ducha. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-torneira/tipoTorneira/gourmet.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-torneira',
    keywords: ['torneira', 'gourmet', 'cozinha', 'peca'],
  },
  {
    slug: 'peca-registro-gaveta',
    nome: 'Registro de gaveta',
    categoria: 'hidraulica',
    precoMinimo: 59.9,
    precoTexto: 'R$ 59,90',
    tipoPreco: 'fixo',
    descricao: 'Registro de gaveta. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/troca-registro/tipoRegistro/registro-gaveta.webp',
    tipo: 'peca',
    servicoRelacionado: 'troca-registro',
    keywords: ['registro', 'gaveta', 'hidraulica', 'peca'],
  },
  {
    slug: 'peca-chuveiro-eletrico',
    nome: 'Chuveiro elétrico',
    categoria: 'eletricista',
    precoMinimo: 129.9,
    precoTexto: 'R$ 129,90',
    tipoPreco: 'fixo',
    descricao: 'Chuveiro elétrico. Peça avulsa — instalação contratada à parte.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/instalacao-chuveiro/tipoServicoChuveiro/instalar-comum.webp',
    tipo: 'peca',
    servicoRelacionado: 'instalacao-chuveiro',
    keywords: ['chuveiro', 'ducha', 'banho', 'peca'],
  },
  {
    slug: 'peca-luminaria-plafon',
    nome: 'Luminária plafon LED',
    categoria: 'eletricista',
    precoMinimo: 89.9,
    precoTexto: 'R$ 89,90',
    tipoPreco: 'fixo',
    descricao: 'Plafon LED. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/instalacao-luminaria/tipoLuminaria/plafon-led.webp',
    tipo: 'peca',
    servicoRelacionado: 'instalacao-luminaria',
    keywords: ['luminaria', 'plafon', 'led', 'luz', 'peca'],
  },
  {
    slug: 'peca-suporte-tv-fixo',
    nome: 'Suporte de TV fixo',
    categoria: 'montador',
    precoMinimo: 59.9,
    precoTexto: 'R$ 59,90',
    tipoPreco: 'fixo',
    descricao: 'Suporte fixo para TV. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/instalacao-suporte-tv/tipoSuporteTv/fixo.webp',
    tipo: 'peca',
    servicoRelacionado: 'instalacao-suporte-tv',
    keywords: ['suporte', 'tv', 'televisao', 'peca'],
  },
  {
    slug: 'peca-suporte-tv-articulado',
    nome: 'Suporte de TV articulado',
    categoria: 'montador',
    precoMinimo: 119.9,
    precoTexto: 'R$ 119,90',
    tipoPreco: 'fixo',
    descricao: 'Suporte articulado para TV. Peça avulsa, sem instalação.',
    garantiaDias: 90,
    imagemUrl: '/opcoes/instalacao-suporte-tv/tipoSuporteTv/articulado.webp',
    tipo: 'peca',
    servicoRelacionado: 'instalacao-suporte-tv',
    keywords: ['suporte', 'tv', 'articulado', 'peca'],
  },
];

export function isPecaSlug(slug: string) {
  return slug.startsWith('peca-') || PECAS_CATALOGO.some((p) => p.slug === slug);
}

export function findPeca(slug: string) {
  return PECAS_CATALOGO.find((p) => p.slug === slug) || null;
}

export function pecasDoServico(slug: string) {
  return PECAS_CATALOGO.filter((p) => p.servicoRelacionado === slug);
}

export function itemPath(item: { tipo?: string; slug: string }) {
  return isPecaSlug(item.slug) || item.tipo === 'peca' ? `/p/${item.slug}` : `/s/${item.slug}`;
}
