/** Catálogo ABS Resolve — fonte: planilha Serviços ABS */

export const CATEGORIAS = [
  { slug: 'eletricista', nome: 'Eletricista', icone: '⚡', cor: '#0033B5' },
  { slug: 'hidraulica', nome: 'Hidráulica', icone: '💧', cor: '#0ea5e9' },
  { slug: 'montador', nome: 'Montador', icone: '🔧', cor: '#6366f1' },
  { slug: 'ar-condicionado', nome: 'Ar-condicionado', icone: '❄️', cor: '#06b6d4' },
  { slug: 'jardinagem', nome: 'Jardinagem', icone: '🌿', cor: '#22c55e' },
  { slug: 'limpeza-pos-obra', nome: 'Limpeza pós-obra', icone: '🧹', cor: '#64748b' },
] as const;

export type TipoPreco = 'fixo' | 'a_partir' | 'sob_orcamento';

export interface ServicoCatalogoDef {
  slug: string;
  categoria: string;
  nome: string;
  precoMinimo: number | null;
  precoTexto: string;
  tipoPreco: TipoPreco;
  garantiaDias: number;
  descricao: string;
  pontos: number;
  ordem: number;
  imagemUrl: string;
}

export const SERVICOS_CATALOGO: ServicoCatalogoDef[] = [
  {
    slug: 'troca-tomada',
    categoria: 'eletricista',
    nome: 'Troca de tomada',
    precoMinimo: 149,
    precoTexto: 'R$ 149',
    tipoPreco: 'fixo',
    garantiaDias: 90,
    descricao: 'Remoção da tomada antiga • Fornecimento de tomada padrão • Instalação • Teste de funcionamento',
    pontos: 1,
    ordem: 1,
    imagemUrl: '/servicos/troca-tomada.png',
  },
  {
    slug: 'troca-interruptor',
    categoria: 'eletricista',
    nome: 'Troca de interruptor',
    precoMinimo: 149,
    precoTexto: 'R$ 149',
    tipoPreco: 'fixo',
    garantiaDias: 90,
    descricao: 'Remoção do interruptor antigo • Instalação do novo • Teste de funcionamento',
    pontos: 1,
    ordem: 2,
    imagemUrl: '/servicos/troca-interruptor.svg',
  },
  {
    slug: 'instalacao-chuveiro',
    categoria: 'eletricista',
    nome: 'Instalação de chuveiro',
    precoMinimo: 199,
    precoTexto: 'R$ 199',
    tipoPreco: 'fixo',
    garantiaDias: 90,
    descricao: 'Remoção do chuveiro antigo • Instalação do novo (cliente fornece) • Verificação do disjuntor • Teste',
    pontos: 2,
    ordem: 3,
    imagemUrl: '/servicos/instalacao-chuveiro.svg',
  },
  {
    slug: 'troca-disjuntor',
    categoria: 'eletricista',
    nome: 'Troca de disjuntor',
    precoMinimo: 169,
    precoTexto: 'R$ 169',
    tipoPreco: 'fixo',
    garantiaDias: 90,
    descricao: 'Remoção do disjuntor antigo • Instalação do novo (cliente fornece) • Teste do quadro',
    pontos: 1,
    ordem: 4,
    imagemUrl: '/servicos/troca-disjuntor.svg',
  },
  {
    slug: 'instalacao-luminaria',
    categoria: 'eletricista',
    nome: 'Instalação de luminária',
    precoMinimo: 159,
    precoTexto: 'R$ 159',
    tipoPreco: 'fixo',
    garantiaDias: 90,
    descricao: 'Fixação • Conexão elétrica • Teste de funcionamento',
    pontos: 2,
    ordem: 5,
    imagemUrl: '/servicos/instalacao-luminaria.png',
  },
  {
    slug: 'instalacao-ventilador-teto',
    categoria: 'eletricista',
    nome: 'Instalação de ventilador de teto',
    precoMinimo: 299,
    precoTexto: 'R$ 299',
    tipoPreco: 'fixo',
    garantiaDias: 90,
    descricao: 'Fixação • Conexão elétrica • Teste de funcionamento',
    pontos: 2,
    ordem: 6,
    imagemUrl: '/servicos/instalacao-ventilador.png',
  },
  {
    slug: 'troca-torneira',
    categoria: 'hidraulica',
    nome: 'Troca de torneira',
    precoMinimo: 179,
    precoTexto: 'R$ 179',
    tipoPreco: 'fixo',
    garantiaDias: 90,
    descricao: 'Remoção da torneira antiga • Fornecimento da torneira padrão • Instalação • Teste',
    pontos: 1,
    ordem: 7,
    imagemUrl: '/servicos/troca-torneira.png',
  },
  {
    slug: 'troca-registro',
    categoria: 'hidraulica',
    nome: 'Troca de registro',
    precoMinimo: 189,
    precoTexto: 'R$ 189',
    tipoPreco: 'fixo',
    garantiaDias: 90,
    descricao: 'Remoção do registro antigo • Instalação do novo • Teste de pressão',
    pontos: 2,
    ordem: 8,
    imagemUrl: '/servicos/troca-registro.svg',
  },
  {
    slug: 'reparo-vazamento',
    categoria: 'hidraulica',
    nome: 'Reparo de vazamento',
    precoMinimo: 249,
    precoTexto: 'A partir de R$ 249',
    tipoPreco: 'a_partir',
    garantiaDias: 90,
    descricao: 'Avaliação técnica • Identificação da causa • Orçamento detalhado • Execução do reparo',
    pontos: 2,
    ordem: 9,
    imagemUrl: '/servicos/reparo-vazamento.svg',
  },
  {
    slug: 'desentupimento-pia',
    categoria: 'hidraulica',
    nome: 'Desentupimento de pia',
    precoMinimo: 199,
    precoTexto: 'R$ 199',
    tipoPreco: 'fixo',
    garantiaDias: 30,
    descricao: 'Avaliação • Desentupimento • Teste de vazão',
    pontos: 1,
    ordem: 10,
    imagemUrl: '/servicos/desentupimento-pia.svg',
  },
  {
    slug: 'desentupimento-vaso',
    categoria: 'hidraulica',
    nome: 'Desentupimento de vaso',
    precoMinimo: 299,
    precoTexto: 'A partir de R$ 299',
    tipoPreco: 'a_partir',
    garantiaDias: 30,
    descricao: 'Avaliação • Desentupimento • Teste de funcionamento',
    pontos: 2,
    ordem: 11,
    imagemUrl: '/servicos/desentupimento-vaso.svg',
  },
  {
    slug: 'instalacao-suporte-tv',
    categoria: 'montador',
    nome: 'Instalação de suporte de TV',
    precoMinimo: 159,
    precoTexto: 'R$ 159',
    tipoPreco: 'fixo',
    garantiaDias: 90,
    descricao: 'Marcação • Fixação • Encaixe da TV • Organização de cabos',
    pontos: 1,
    ordem: 12,
    imagemUrl: '/servicos/suporte-tv.svg',
  },
  {
    slug: 'instalacao-prateleira',
    categoria: 'montador',
    nome: 'Instalação de prateleira',
    precoMinimo: 149,
    precoTexto: 'R$ 149',
    tipoPreco: 'fixo',
    garantiaDias: 30,
    descricao: 'Marcação • Fixação • Ajustes finais',
    pontos: 1,
    ordem: 13,
    imagemUrl: '/servicos/prateleira.svg',
  },
  {
    slug: 'montagem-moveis-simples',
    categoria: 'montador',
    nome: 'Montagem de móvel simples',
    precoMinimo: 249,
    precoTexto: 'R$ 249',
    tipoPreco: 'fixo',
    garantiaDias: 30,
    descricao: 'Conferência das peças • Montagem • Fixação e ajustes',
    pontos: 2,
    ordem: 14,
    imagemUrl: '/servicos/montagem-moveis.svg',
  },
  {
    slug: 'montagem-guarda-roupa',
    categoria: 'montador',
    nome: 'Montagem de guarda-roupa',
    precoMinimo: 499,
    precoTexto: 'R$ 499',
    tipoPreco: 'fixo',
    garantiaDias: 30,
    descricao: 'Conferência das peças • Montagem completa • Nivelamento • Ajustes finais',
    pontos: 3,
    ordem: 15,
    imagemUrl: '/servicos/guarda-roupa.svg',
  },
  {
    slug: 'instalacao-persiana',
    categoria: 'montador',
    nome: 'Instalação de persiana',
    precoMinimo: 179,
    precoTexto: 'R$ 179',
    tipoPreco: 'fixo',
    garantiaDias: 30,
    descricao: 'Marcação • Fixação • Instalação • Teste de funcionamento',
    pontos: 2,
    ordem: 16,
    imagemUrl: '/servicos/persiana.png',
  },
  {
    slug: 'limpeza-ar-split',
    categoria: 'ar-condicionado',
    nome: 'Limpeza preventiva (split)',
    precoMinimo: 249,
    precoTexto: 'R$ 249',
    tipoPreco: 'fixo',
    garantiaDias: 30,
    descricao: 'Limpeza de filtros • Higienização • Checagem de gás • Teste',
    pontos: 2,
    ordem: 17,
    imagemUrl: '/servicos/limpeza-ar.svg',
  },
  {
    slug: 'instalacao-ar-split',
    categoria: 'ar-condicionado',
    nome: 'Instalação de ar-condicionado split',
    precoMinimo: null,
    precoTexto: 'Sob orçamento',
    tipoPreco: 'sob_orcamento',
    garantiaDias: 90,
    descricao: 'Avaliação técnica • Suporte e tubulação • Instalação • Teste de funcionamento',
    pontos: 4,
    ordem: 18,
    imagemUrl: '/servicos/instalacao-ar.svg',
  },
  {
    slug: 'poda-jardim',
    categoria: 'jardinagem',
    nome: 'Poda e limpeza de jardim',
    precoMinimo: 159,
    precoTexto: 'R$ 159',
    tipoPreco: 'fixo',
    garantiaDias: 0,
    descricao: 'Poda • Limpeza • Remoção de resíduos',
    pontos: 2,
    ordem: 19,
    imagemUrl: '/servicos/jardim.svg',
  },
  {
    slug: 'limpeza-pos-obra',
    categoria: 'limpeza-pos-obra',
    nome: 'Limpeza pós-obra',
    precoMinimo: 15,
    precoTexto: 'A partir de R$ 15/m²',
    tipoPreco: 'a_partir',
    garantiaDias: 0,
    descricao: 'Avaliação no local • Limpeza pesada • Remoção de resíduos finos',
    pontos: 3,
    ordem: 20,
    imagemUrl: '/servicos/limpeza-obra.svg',
  },
];

export const PONTUACAO_POR_SLUG: Record<string, number> = Object.fromEntries(
  SERVICOS_CATALOGO.map((s) => [s.slug, s.pontos])
);
